services:
  web:
    build: .
    container_name: eremont
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - static_volume:/web/static
      - media_volume:/web/media
    env_file:
      - .env
    command: >
      /bin/sh -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn -b 0.0.0.0:5000 eremont.wsgi:application"

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes: 
      - ./pg/data:/var/lib/postgresql/data
      - ./pg/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - static_volume:/web/static
      - media_volume:/web/media
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:

    